from .client import ClientReadSerializer,ClientWriteSerializer
from .invoice import InvoiceReadSerializer,InvoiceWriteSerializer
from .project import ProjectWriteSerializer,ProjectReadSerializer
from .meeting import MeetingWriteSerializer,MeetingReadSerializer